name: Deploy to GithubPages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install wasm target and trunk
      run: |
        rustup target add wasm32-unknown-unknown
        cargo install trunk
        trunk config show
    - name: Build the app
      run: trunk build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
          folder: dist

